### PR TITLE
restore dunecontrol compatibility after the opm-cmake -> opm-common rename

### PR DESCRIPTION
**Pull request by andlaus**
also fixes the stub build system to detect opm-common.

### CODE REVIEW

**Comment by akva2** [comment]
this module is deprecated.

**Comment by akva2** [comment]
argh, wrong button, and too early at that. ... but it seems that we still want to keep it building.

**Comment by alfbr** [comment]
It is deprecated, som I suggest not putting any energy into making it compile.

**Comment by andlaus** [comment]
in this case, wouldn't it be better to either delete it outright, rename it to `opm-legacy-benchmarks` or remove the build system?

(when was it decided that this is deprecated, btw?)

**Comment by alfbr** [comment]
Yes, but as long as it is used in phoronix test suite, we should not delete it. It was decided when Arne Morten moved the used benchmark to opm-upscaling after years of inactivity. If you feel for keeping it, please voice your concerns.

**Comment by andlaus** [comment]
> Yes, but as long as it is used in phoronix test suite, we should not delete it.

is that some old version or is it a recent one? i.e. does the phoronix test suite update its OPM packages occasionally?

**Comment by alfbr** [comment]
Old version, compiled from source.

**Comment by andlaus** [comment]
that means the repo can be deleted?

**Comment by alfbr** [comment]
Not as long as PTS downloads source code from it.

**Comment by atgeirr** [comment]
> Not as long as PTS downloads source code from it

Does this still apply? Anyway I'll merge these final PRs and close remaining issues on this repo to prevent them from showing up in the overviews.

**Comment by alfbr** [comment]
No, we have now updated the PTS test. Allow me a couple of days to check out the current state. Then, unless there are objections here, I will delete the repository.

**Pull request merged**
