### PR TITLE
changed: sync with renaming to opm-common

### PR DESCRIPTION
**Pull request by babrodtk**
*Do not merge* before renaming with friends has happened.

### CODE REVIEW

**Comment by alfbr** [comment]
I suggest closing rhis one.

**Comment by babrodtk** [comment]
This PR models the pull requests in sibling repositories (opm-material, opm-autodiff, etc.) to update with the renaming of opm-cmake to opm-common. Can you explain your view on why it should be closed?

**Comment by akva2** [comment]
this module is deprecated. the benchmark has been integrated in opm-upscaling.

**Comment by alfbr** [comment]
The benchmarks repo is here for historical reasons, we have moved the benchmark into opm-upscaling. Once phoronix test suite is updated, we will consider deleting the repo. Hence there is no need to spend resources keeping this repo alive.

**Comment by babrodtk** [comment]
OK, feel free to close it.

**Comment by babrodtk** [comment]
Closing pull request

**Pull request closed without merging**
